apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: user-service
    app.kubernetes.io/managed-by: Helm
spec:
  type: {{ .Values.service.type }}
  selector:
    app: user-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "user-service" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: user-service
    app.kubernetes.io/managed-by: Helm
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
