image:
  repository: 444062204470.dkr.ecr.us-east-1.amazonaws.com/platform/user-service
  tag: latest
replicaCount: 2
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::444062204470:role/user-service-secrets-role
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
